### PR TITLE
Merge Sidd's January 2021 Citations

### PR DESCRIPTION
**Pull request by siddk**
Citations from January 2021 Submissions - unfortunately, a few conflicts:

- `data/pliang.rb` - `antol2015vqav1` is the wrong cite for VQA-v1; commented and replaced with `agrawal2015vqa1`
- `data/pliang.rb` - `settles2010active` is wrong year for active learning survey; replaced with `settles2009active`
- `data/joberant.rb` - Major formatting issue with `krishna2017visual`; removed and replaced with correctly formatted cite.
- `data/ice.rb` - `suhr2018nlvr2` is outdated; commented and replaced with `suhr2019nlvr2` (ACL 2019)
- `data/evan.rb` - `andreas2016modular` is outdated; removed and replaced with `andreas2017sketches` (ICML 2017)

### CODE REVIEW

**Review by percyliang — APPROVED** [review]
You can remove all the `nil`s.

**Comment by siddk** [comment]
Done - able to merge & close.

**Comment by percyliang** [comment]
Why are there some many diffs in all.bib?  It seems like some things got reordered?  Is there non-determinism?

**Comment by siddk** [comment]
Not sure at all - is there possibly non-determinism based on ruby versions?

**Comment by percyliang** [comment]
I think it's actually fine.

**Pull request merged**
